### ISSUE TITLE
How Do I Push Into Production?

### ISSUE THREAD

**Issue by kivo360** [Draichi/altcoin-bot-advisor#10]
I was looking into these algorithms and was wondering how to bring RL into production. Google doesn't have anything on the subject. How do I put this algorithm into production?

**Comment by Draichi** [comment]
This is something I'm working on a couple weeks, you basically need to bind the agent's output with your favorite exchange API.

Example:
If you trained a model to operate with BTC/USDT, ETH/USDT and LTC/USDT the agent's output will be: 
- a float between 0 and 7: each number corresponding to an action, 7 in the total because you have the action to do nothing, buy BTC, sell BTC, buy ETH, sell ETH, buy LTC, sell LTC, 7 in total.
- a float between 0 and 1: this is the portfolio amout you gonna buy, or sell, zero is nothing 1 is 100%.

So, you gonna have to open an order accordingly to this outputs.
 
I'm doing a lot of refactor, the new release is gonna be much easier to plug and play, I hope to make it easier to contribute too
