### ISSUE TITLE
About action_type

### ISSUE THREAD

**Issue by kevinljw** [Draichi/altcoin-bot-advisor#17]
Hello. Thank you for sharing such an interesting project. After reading your program, I am a little confused about the approach in the function:`_buy_or_sell()` in `core_env.py`. Here's my question: why the decision to buy or sell is determined by inequality (like: `if action_type <index / 2 + 1 `...) rather than directly using `action_type`?

What is the mechanism here? I think this will result in some assts that will not be used to buy or sell.

What I also want to know is the `action_type` defined here. If my assets list is ['BTC', 'ETH', 'LTC', 'BNB'], what will be in the action_type? Is it hold, buy BTC, sell BTC, buy ETH, sell ETH, buy LTC, sell LTC, buy BNB, sell BNB, 9 in total? Is there an actual order? 

Thank you so much and look forward to your reply!

**Comment by Draichi** [comment]
Hello, @kevinljw 

>why the decision to buy or sell is determined by inequality (like: if action_type <index / 2 + 1 ...) rather than directly using action_type?

Well, your assets list multiplied by 2:

```python
for index, asset in enumerate(self.assets_list*2):
```
So, your assets list will be like
 ```python
['BTC', 'ETH', 'BTC', 'ETH']
# buy btc, buy eth, sell btc, sell eth
# we do not compute hold action because there's no action on holding
```

So here we divide by 2 to get the _buy half_ of the list (+1 because the list start on 0)
```python
action_type <index / 2 + 1
```
if the action type is in the buy half we will buy it, if not we'll catch it on the next `if` and sell it, action tyoes that do not fit in this list are interpreted as _hold actions_

***

> ['BTC', 'ETH', 'LTC', 'BNB'], what will be in the action_type?

The action type will be a integer from zero to `len(self.assets_list) * 2`
```python
# action space = buy and sell for each asset, plus hold position
action_space = 1 + len(self.assets_list) * 2
```
The order will be:
- 0 = hold
- 1 ~ 4 = buy (in the respective order of your assets_list. ex: 4 => buy BNB)
- 5 ~ 8 = sell (in the respective order of your assets_list. ex: 8 => sell BNB)

Hope this help,
Lucas :feelsgood:
